/*
GENERAMOS VENTAS ALEATORIAS Y CONSULTAMOS VALOR DE IMPUESTO EN EL 2021
*/
CALL sp_venta('20210619', 30, 100);

/**/
SELECT YEAR(FECHA), CEIL(SUM(IMPUESTO * (CANTIDAD * PRECIO))) 
AS RESULTADO
FROM facturas F
INNER JOIN items I ON F.NUMERO = I.NUMERO
WHERE YEAR(FECHA) = 2021
GROUP BY YEAR(FECHA);